apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: gone-hog-hello
  labels:
    app: hello
    chart: hello-0.1.0
    release: gone-hog
    heritage: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
      release: gone-hog
  template:
    metadata:
      labels:
        app: hello
        release: gone-hog
    spec:
      containers:
        - name: hello
          image: "nginx:stable"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}
