apiVersion: v1
kind: Service
metadata:
  name: gone-hog-hello
  labels:
    app: hello
    chart: hello-0.1.0
    release: gone-hog
    heritage: Tiller
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      nodePort: 30088
      name: http
  selector:
    app: hello
    release: gone-hog

