apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: hopping-squid-c7nx
  labels:
    app: c7nx
    chart: c7nx-0.1.0
    release: hopping-squid
    heritage: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: c7nx
      release: hopping-squid
  template:
    metadata:
      labels:
        app: c7nx
        release: hopping-squid
    spec:
      volumes:
        - name: vol
          hostPath:
            path: /sys/fs/cgroup
      containers:
        - name: c7nx
          image: "c7nx:latest"
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: vol
            mountPath: /sys/fs/cgroup
            readOnly: true
          securityContext:
            privileged: true
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: myport
              containerPort: 3389
              protocol: TCP
          resources:
            {}

