apiVersion: v1
kind: Service
metadata:
  name: measly-llama-scilab
  labels:
    app: scilab
    chart: scilab-0.1.0
    release: measly-llama
    heritage: Tiller
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8080
      protocol: TCP
      nodePort: 30011
      name: http
  selector:
    app: scilab
    release: measly-llama
