apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "bachviodb.fullname" . }}
  labels:
    app: {{ template "bachviodb.name" . }}
    chart: {{ template "bachviodb.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "bachviodb.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "bachviodb.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        restartPolicy: Always
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"
        ports:
        - name: http
          containerPort: 3306
          protocol: TCP
        resources: {}
      volumes:
      - name: data
        hostPath:
          path: /home/linux/helm/bachviodata
